### ISSUE TITLE
Task Wait for DNS entries to propagate not stable

### ISSUE THREAD

**Issue by mr-ssd** [felixfontein/ansible-acme#57]
The task named "[Wait for DNS entries to propagate](https://github.com/felixfontein/ansible-acme/blob/c44d7a2c48b074d053b97f5dc46fdb05f8ae1b53/roles/acme_certificate/tasks/dns-route53-create.yml#LL23C9-L23C42)" in role [acme_certificate](https://github.com/felixfontein/ansible-acme/tree/main/roles/acme_certificate) is not stable when using with Route53. 

I suggest we should change **wait: false** to **wait: true** to wait until the changes have been replicated to all Amazon Route 53 DNS servers before we check for the TXT record.

**Comment by felixfontein** [comment]
Using `wait: true` is not a good solution either, since that makes the role incredibly slow when using Route53.

**Comment by mr-ssd** [comment]
Can we change it as an option in a variable?

**Comment by felixfontein** [comment]
I would prefer not to add a config for that. I started some work in the aws collections to make it possible to solve this in a cleaner way: https://github.com/ansible-collections/amazon.aws/pull/1683 https://github.com/ansible-collections/community.aws/pull/1904

**Comment by mr-ssd** [comment]
@felixfontein thank you for the update. Should this case be closed?

**Comment by felixfontein** [comment]
I would keep this issue open, as the problem hasn't been resolved yet.

**Comment by felixfontein** [comment]
https://github.com/ansible-collections/community.aws/pull/1904 together with https://github.com/felixfontein/ansible-acme/pull/62 fixes this, and is pretty efficient as well. I tested it this morning with a larger set of certificates (many of them with Route 53 DNS validation), and it worked as expected.
